image: node:latest

cache:
    paths:
        - node_modules/
        - yarn.lock

stages:
    - install
    - deploy

install:
    only:
        # - main
        - dev
    stage: install
    script:
        - apt-get update
        - apt-get install -y yarn
        - yarn

deploy:
    image: ruby:latest
    only:
        # - main
        - dev
    stage: deploy
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
